apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: strimzi
    release: my-prometheus
  name: kafka-metrics
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
  selector:
    matchExpressions:
      - key: strimzi.io/kind
        operator: In
        values:
          - Kafka
